#ifndef REDISBASEMODULE_GLOBAL_H
#define REDISBASEMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REDISBASEMODULE_LIBRARY)
#  define REDISBASEMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define REDISBASEMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REDISBASEMODULE_GLOBAL_H
